config/routes.rb
Rails.application.routes.draw do
  root :to => "timelines#index"
  
  resources :turns do
    resources :turn_details
  end
  resources :message_groups do
    resources :messages
  end


  resources :timelines do
    member do
      get :liking_users
    end
    resources :replies
  end
  resources :profiles
  resources :expenses do
  	resources :costs
  end

  devise_for :users, skip: [:sessions, :registrations] #deviseのデフォルトのpathを削除
  devise_scope :user do
    root :to => "devise/sessions#new"
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'sign_up' => 'devise/registrations#new', as: :new_user_registration
    post 'sign_up' => 'devise/registrations#create', as: :user_registration
  end

  resources :messages
  resources :profiles
  resources :groups
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# likes関連
  post '/like/:timeline_id' => 'likes#like', as: 'like'
  delete '/unlike/:timeline_id' => 'likes#unlike', as: 'unlike'

end

app/models/reply.rb
# == Schema Information
#
# Table name: replies
#
#  id          :integer          not null, primary key
#  comment     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  timeline_id :integer
#
# Indexes
#
#  index_replies_on_timeline_id  (timeline_id)
#

class Reply < ApplicationRecord
	belongs_to :user
	belongs_to :timeline
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  # GET /replies
  # GET /replies.json
  def index
    @timeline = Timeline.where(:id => params[:timeline_id]).first
    @replies = @timeline.replies.all
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
  end

  # GET /replies/new
  def new
    @timeline = Timeline.where(:id => params[:timeline_id]).first
    @reply = @timeline.replies.build
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
    @timeline = Timeline.where(:id => params[:timeline_id]).first
    @timelines = Timeline.all
    @reply = @timeline.replies.build(reply_params)
    @reply.user = current_user

    respond_to do |format|
      if @reply.save
        format.html { redirect_to timelines_url, notice: 'Reply was successfully created.' }
        format.json { render :show, status: :created, location: @reply }
      else
        format.html { render :new }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to [@timeline,@reply], notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to timeline_replies_url, notice: 'Reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
      @timeline = Timeline.where(:id => params[:timeline_id]).first
      @reply = @timeline.replies.where(:id => params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reply_params
      params.require(:reply).permit(:comment, :timeline_id)
    end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_for [timeline, reply] do |f| %>
  <% if reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% reply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit "コメントする" %>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing Reply</h1>

<%= render 'form', reply: @reply %>

<%= link_to 'Show', timeline_reply_path(@timeline, @reply) %> |
<%= link_to 'Back', timeline_replies_path %>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Replies</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.comment %></td>
        <td><%= reply.user.profile.name %></td>
        <td><%= link_to 'Show', timeline_reply_path(@timeline,reply) %></td>
        <td><%= link_to 'Edit', edit_timeline_reply_path(@timeline,reply) %></td>
        <td><%= link_to 'Destroy', timeline_reply_path(@timeline, reply), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_timeline_reply_path %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= render 'form', timeline: @reply.timeline, reply: @reply %>

<%= link_to 'Back', timeline_replies_path %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment:</strong>
  <%= @reply.comment %>
</p>

<%= link_to 'Edit', edit_timeline_reply_path(@timeline, @reply) %> |
<%= link_to 'Back', timeline_replies_path %>