config/routes.rb
Rails.application.routes.draw do
  root :to => "timelines#index"
  
  resources :turns do
    resources :turn_details
  end
  resources :message_groups do
    resources :messages
  end


  resources :timelines do
    member do
      get :liking_users
    end
    resources :replies
  end
  resources :profiles
  resources :expenses do
  	resources :costs
  end

  devise_for :users, skip: [:sessions, :registrations] #deviseのデフォルトのpathを削除
  devise_scope :user do
    root :to => "devise/sessions#new"
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'sign_up' => 'devise/registrations#new', as: :new_user_registration
    post 'sign_up' => 'devise/registrations#create', as: :user_registration
  end

  resources :messages
  resources :profiles
  resources :groups
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# likes関連
  post '/like/:timeline_id' => 'likes#like', as: 'like'
  delete '/unlike/:timeline_id' => 'likes#unlike', as: 'unlike'

end

app/models/turn_detail.rb
# == Schema Information
#
# Table name: turn_details
#
#  id         :integer          not null, primary key
#  when       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  turn_id    :string
#

class TurnDetail < ApplicationRecord
	has_many :users, through: :turn_detail_users 
	has_many :turn_detail_users, inverse_of: :turn_details
	has_many :turns, through: :turn_detail_users
	accepts_nested_attributes_for :turn_detail_users
	belongs_to :turn, inverse_of: :turn_details, optional: true
	validates :when, presence: true
end

app/controllers/turn_details_controller.rb
class TurnDetailsController < ApplicationController
  before_action :set_turn_detail, only: [:show, :edit, :update, :destroy]

  # GET /turn_details
  # GET /turn_details.json
  def index
    @turn_details = TurnDetail.all
  end

  # GET /turn_details/1
  # GET /turn_details/1.json
  def show
  end

  # GET /turn_details/new
  def new
    @turn_detail = TurnDetail.new
  end

  # GET /turn_details/1/edit
  def edit
  end

  # POST /turn_details
  # POST /turn_details.json
  def create
    @turn_detail = TurnDetail.new(turn_detail_params)

    respond_to do |format|
      if @turn_detail.save
        format.html { redirect_to @turn_detail, notice: 'Turn detail was successfully created.' }
        format.json { render :show, status: :created, location: @turn_detail }
      else
        format.html { render :new }
        format.json { render json: @turn_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turn_details/1
  # PATCH/PUT /turn_details/1.json
  def update
    respond_to do |format|
      if @turn_detail.update(turn_detail_params)
        format.html { redirect_to @turn_detail, notice: 'Turn detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @turn_detail }
      else
        format.html { render :edit }
        format.json { render json: @turn_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turn_details/1
  # DELETE /turn_details/1.json
  def destroy
    @turn_detail.destroy
    respond_to do |format|
      format.html { redirect_to turn_details_url, notice: 'Turn detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turn_detail
      @turn_detail = TurnDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turn_detail_params
      params.require(:turn_detail).permit(:when, :user_id, :turn_id)
    end
end

app/helpers/turn_details_helper.rb
module TurnDetailsHelper
end

app/views/turn_details/_form.html.erb
<%= form_for(turn_detail) do |f| %>
  <% if turn_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(turn_detail.errors.count, "error") %> prohibited this turn_detail from being saved:</h2>

      <ul>
      <% turn_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :when %>
    <%= f.text_field :when %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/turn_details/edit.html.erb
<h1>Editing Turn Detail</h1>

<%= render 'form', turn_detail: @turn_detail %>

<%= link_to 'Show', @turn_detail %> |
<%= link_to 'Back', turn_details_path %>

app/views/turn_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turn Details</h1>

<table>
  <thead>
    <tr>
      <th>When</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @turn_details.each do |turn_detail| %>
      <tr>
        <td><%= turn_detail.when %></td>
        <td><%= turn_detail.user_id %></td>
        <td><%= link_to 'Show', turn_detail %></td>
        <td><%= link_to 'Edit', edit_turn_detail_path(turn_detail) %></td>
        <td><%= link_to 'Destroy', turn_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Turn Detail', new_turn_detail_path %>

app/views/turn_details/new.html.erb
<h1>New Turn Detail</h1>

<%= render 'form', turn_detail: @turn_detail %>

<%= link_to 'Back', turn_details_path %>

app/views/turn_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>When:</strong>
  <%= @turn_detail.when %>
</p>

<p>
  <strong>User:</strong>
  <%= @turn_detail.user_id %>
</p>

<%= link_to 'Edit', edit_turn_detail_path(@turn_detail) %> |
<%= link_to 'Back', turn_details_path %>