config/routes.rb
Rails.application.routes.draw do
  root :to => "timelines#index"
  
  resources :turns do
    resources :turn_details
  end
  resources :message_groups do
    resources :messages
  end


  resources :timelines do
    member do
      get :liking_users
    end
    resources :replies
  end
  resources :profiles
  resources :expenses do
  	resources :costs
  end

  devise_for :users, skip: [:sessions, :registrations] #deviseのデフォルトのpathを削除
  devise_scope :user do
    root :to => "devise/sessions#new"
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'sign_up' => 'devise/registrations#new', as: :new_user_registration
    post 'sign_up' => 'devise/registrations#create', as: :user_registration
  end

  resources :messages
  resources :profiles
  resources :groups
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# likes関連
  post '/like/:timeline_id' => 'likes#like', as: 'like'
  delete '/unlike/:timeline_id' => 'likes#unlike', as: 'unlike'

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string
#  detail     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Group < ApplicationRecord
	has_many :user_groups, inverse_of: :group
	has_many :user, through: :user_groups
	accepts_nested_attributes_for :user_groups, allow_destroy: :true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
    @group.user_groups.build
    @users = User.all.map { |u| UserGroup.new({user_id: u.id})} #user_groupの空のインスタンスを作る
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :detail, user_groups_attributes: [:id, :user_id])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(group) do |f| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :detail %>
    <%= f.text_area :detail %>
  </div>

  <%= f.fields_for :user_groups, @users do |ug| %>
    <div>
      <%= ug.check_box :user_id, {}, ug.object.user_id, false %>
      <%= ug.label ug.object.user.profile.name %>
      <%= ug.hidden_field :id %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h2>グループ一覧</h2>

<table>
  <thead>
    <tr>
      <th>グループ名</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.detail %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="waves-effect waves-light btn new_group"><%= link_to 'グループを作成', new_group_path %></div>

app/views/groups/new.html.erb
<h2>グループを作る</h2>

<%= form_for @group do |f| %>
	<div class="row">
		<div class="input-field col s12">
			<%= f.text_field :name %>
			<%= f.label :name %>
		</div>
		<div class="input-field col s12">
			<%= f.text_area :detail %>
			<%= f.label :detail %>
		</div>
	</div>
	<div id="users"></div>
	<a href="#candidate-modal" class="modal-trigger waves-effect waves-light btn">
		メンバーを選択
	</a>
	<div class="waves-effect btn"><%= f.submit %></div>
<% end %>

  
<div id="candidate-modal" class="modal">
	 <div class="modal-content">
	 	<h4>select user</h4>
    <div class="section"></div>
    <ul class="collection">
    	<% User.all.each do |u| %>
        <li class="collection-item avatar" data-user-id="<%= u.id %>">
          <%= profile_image klz: 'circle' %>
          <p>
          	<%= u.profile.name %>
          </p> 
        </li>
      <% end %>
    </ul>
      
	 </div>
    
  <div class="modal-footer">
  	<a class="modal-action modal-close waves-effect waves-green btn-flat cancel">Cancel</a>
    <a class="waves-effect waves-green btn-flat ok" data-attribute-name="group[user_group_attributes][][user_id]">OK</a>
  </div>
    
</div>
<%= link_to '戻る', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @group.detail %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>