config/routes.rb
Rails.application.routes.draw do
  root :to => "timelines#index"
  
  resources :turns do
    resources :turn_details
  end
  resources :message_groups do
    resources :messages
  end


  resources :timelines do
    member do
      get :liking_users
    end
    resources :replies
  end
  resources :profiles
  resources :expenses do
  	resources :costs
  end

  devise_for :users, skip: [:sessions, :registrations] #deviseのデフォルトのpathを削除
  devise_scope :user do
    root :to => "devise/sessions#new"
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
    get 'sign_up' => 'devise/registrations#new', as: :new_user_registration
    post 'sign_up' => 'devise/registrations#create', as: :user_registration
  end

  resources :messages
  resources :profiles
  resources :groups
  resources :events

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# likes関連
  post '/like/:timeline_id' => 'likes#like', as: 'like'
  delete '/unlike/:timeline_id' => 'likes#unlike', as: 'unlike'

end

app/models/cost.rb
# == Schema Information
#
# Table name: costs
#
#  id         :integer          not null, primary key
#  subject    :string
#  cost       :integer
#  detail     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  expense_id :integer
#

class Cost < ApplicationRecord
	belongs_to :expense, inverse_of: :costs
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
    
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @expense = Expense.find params[:expense_id]
    @cost = Cost.new(cost_params)
    @cost.expense = @expense

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @expense, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:subject, :cost, :detail)
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_for(cost, url: expense_costs_path(expense)) do |f| %>
  <% if cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
      <% cost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.number_field :cost %>
  </div>

  <div class="field">
    <%= f.label :detail %>
    <%= f.text_area :detail %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1>Editing Cost</h1>

<%= render 'layouts/header' %>
<%= render 'layouts/sidebar' %>

<%= render 'form', cost: @cost %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Costs</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Cost</th>
      <th>Detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= cost.subject %></td>
        <td><%= cost.cost %></td>
        <td><%= cost.detail %></td>
        <td><%= link_to 'Show', cost %></td>
        <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
        <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cost', new_cost_path %>

app/views/costs/new.html.erb
<h1>New Cost</h1>


<%= render 'form', cost: @cost %>

<%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Subject:</strong>
  <%= @cost.subject %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @cost.cost %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @cost.detail %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>